### PR TITLE
Add Mongo support for datasource reading.

### PR DESCRIPTION
**Pull request by jmalvarezf**
This is the other part of the development we have done to support MongoDB as the backend database for analytics. This part reads the configuration of the datasource for MongoDB support. 
As I stated in the other pull request, all comments and thoughts are very welcome.

Jose Maria.

### CODE REVIEW

**Comment by gimantha** [comment]
Hi Jose Maria,
How did you test mongo db support? Did you copy the components and mongo related jars to lib to test?
I cannot find the feature for the mongo.

**Comment by jmalvarezf** [comment]
Hello Gimantha,

I had a container with mongoDB, and I tested against that. This PR comes along this other, where we add support for MongoDB in analytics:

https://github.com/wso2/carbon-analytics/pull/225

Basically we copied all the jar files into repository/components/lib (datasource reader, analytics and mongo driver).

Best regards,

**Comment by jmalvarezf** [comment]
Deleted author tags and license added.

**Comment by madhawa-gunasekara** [comment]
Hi @jmalvarezf ,
Thanks for your contribution. This looks good to me. btw Shall we add other authentication types as well. Currently, you have supported the default behaviour. you can follow this document for your reference.

[1] http://mongodb.github.io/mongo-java-driver/3.4/driver/tutorials/authentication/

**Comment by jmalvarezf** [comment]
Hello @madhawa-gunasekara,

Although all these methods could be used via url configuration (that was my first approach), I've added a new configuration entry called "authenticationMethod", to support explicitly other auth methods in the config, as you suggested. Hope it's ok.

Thank you,

**Comment by madhawa-gunasekara** [comment]
@jmalvarezf Nice :+1:

**Comment by jmalvarezf** [comment]
I've added the dependencies into master pom.xml, as I did for carbon-analytics PR.

**Comment by jmalvarezf** [comment]
@gimantha it is done. Thanks!

**Pull request merged**
