### PR TITLE
[EI-279] Rename Dataservice task schduling UI to "DS Scheduled task"

### PR DESCRIPTION
**Pull request by vinok88**
Since there are two task UIs one of them is renamed. Fixed
https://github.com/wso2/product-ei/issues/279

### CODE REVIEW

**Comment by bsenduran** [comment]
@vinok88 how about having a slightly different icon too

**Comment by vinok88** [comment]
@bsenduran, any suggestions? change the color?

**Comment by bsenduran** [comment]
having a database icon, similar to Generate, create upload links

**Comment by vinok88** [comment]
+1

**Comment by bsenduran** [comment]
Icon changed with https://github.com/wso2/carbon-data/pull/152

**Pull request merged**
